import type { LocalWrite, RemoteMetadata, RemoteRow, RemoteState } from "./types.js";

export const mockLocalWrites: LocalWrite[] = [
  {
    writeId: "write_001",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_001",
    actorId: "actor_hash_001",
    table: "documents",
    primaryKey: "doc_001",
    operation: "insert",
    localVersion: 11,
    baseRemoteVersion: 10,
    payloadHash: "hash_doc_001",
    timestamp: "2026-07-06T09:00:00.000Z",
    networkState: "online",
    schemaVersion: 5,
  },
  {
    writeId: "write_002",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_001",
    actorId: "actor_hash_002",
    table: "documents",
    primaryKey: "doc_002",
    operation: "update",
    localVersion: 12,
    baseRemoteVersion: 11,
    payloadHash: "hash_doc_002",
    timestamp: "2026-07-06T09:02:00.000Z",
    networkState: "offline",
    schemaVersion: 5,
  },
  {
    writeId: "write_003",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_001",
    actorId: "actor_hash_003",
    table: "documents",
    primaryKey: "doc_003",
    operation: "update",
    localVersion: 13,
    baseRemoteVersion: 12,
    payloadHash: "hash_doc_003",
    timestamp: "2026-07-06T09:04:00.000Z",
    networkState: "transient_failure",
    schemaVersion: 5,
  },
  {
    writeId: "write_004",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_001",
    actorId: "actor_hash_004",
    table: "documents",
    primaryKey: "doc_004",
    operation: "update",
    localVersion: 14,
    baseRemoteVersion: 4,
    payloadHash: "hash_doc_004",
    timestamp: "2026-07-06T09:06:00.000Z",
    networkState: "online",
    schemaVersion: 5,
  },
  {
    writeId: "write_005",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_002",
    actorId: "actor_hash_005",
    table: "projects",
    primaryKey: "project_001",
    operation: "update",
    localVersion: 3,
    baseRemoteVersion: 3,
    payloadHash: "hash_project_001",
    timestamp: "2026-07-06T09:08:00.000Z",
    networkState: "online",
    schemaVersion: 4,
  },
  {
    writeId: "write_006",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_003",
    actorId: "actor_hash_006",
    table: "vector_memory",
    primaryKey: "memory_001",
    operation: "vector_memory_upsert",
    localVersion: 21,
    baseRemoteVersion: 21,
    payloadHash: "hash_memory_001",
    timestamp: "2026-07-06T09:10:00.000Z",
    networkState: "online",
    schemaVersion: 5,
    embeddingModelVersion: 3,
  },
  {
    writeId: "write_007",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_003",
    actorId: "actor_hash_007",
    table: "tasks",
    primaryKey: "task_001",
    operation: "delete",
    localVersion: 9,
    baseRemoteVersion: 8,
    payloadHash: "hash_task_001",
    timestamp: "2026-07-06T09:12:00.000Z",
    networkState: "online",
    schemaVersion: 5,
  },
  {
    writeId: "write_008",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_004",
    actorId: "actor_hash_008",
    table: "sessions",
    primaryKey: "session_001",
    operation: "update",
    localVersion: 6,
    baseRemoteVersion: 6,
    payloadHash: "hash_session_001",
    timestamp: "2026-07-06T09:14:00.000Z",
    networkState: "online",
    schemaVersion: 5,
  },
  {
    writeId: "write_009",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_005",
    actorId: "actor_hash_009",
    table: "notes",
    primaryKey: "note_001",
    operation: "update",
    localVersion: 18,
    baseRemoteVersion: 14,
    payloadHash: "hash_note_001",
    timestamp: "2026-07-06T09:16:00.000Z",
    networkState: "online",
    schemaVersion: 5,
  },
  {
    writeId: "write_010",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_batch_001",
    actorId: "actor_hash_010",
    table: "batch_items",
    primaryKey: "batch_001",
    operation: "insert",
    localVersion: 22,
    baseRemoteVersion: 20,
    payloadHash: "hash_batch_001",
    timestamp: "2026-07-06T09:18:00.000Z",
    networkState: "online",
    schemaVersion: 5,
  },
  {
    writeId: "write_011",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_batch_001",
    actorId: "actor_hash_011",
    table: "batch_items",
    primaryKey: "batch_002",
    operation: "update",
    localVersion: 23,
    baseRemoteVersion: 21,
    payloadHash: "hash_batch_002",
    timestamp: "2026-07-06T09:18:30.000Z",
    networkState: "online",
    schemaVersion: 5,
  },
  {
    writeId: "write_012",
    databaseId: "db_agent_001",
    tenantId: "tenant_hash_batch_001",
    actorId: "actor_hash_012",
    table: "cache_entries",
    primaryKey: "cache_001",
    operation: "update",
    localVersion: 24,
    baseRemoteVersion: 18,
    payloadHash: "hash_cache_001",
    timestamp: "2026-07-06T09:20:00.000Z",
    networkState: "online",
    schemaVersion: 5,
  },
];

export const mockRemoteStates: Record<string, RemoteState> = {
  write_001: {
    rows: [],
  },
  write_002: {
    rows: [
      {
        databaseId: "db_agent_001",
        table: "documents",
        primaryKey: "doc_002",
        remoteVersion: 11,
        lastUpdatedAt: "2026-07-06T08:59:00.000Z",
        schemaVersion: 5,
        payloadHash: "hash_doc_002_remote",
      },
    ],
  },
  write_003: {
    rows: [
      {
        databaseId: "db_agent_001",
        table: "documents",
        primaryKey: "doc_003",
        remoteVersion: 12,
        lastUpdatedAt: "2026-07-06T08:58:00.000Z",
        schemaVersion: 5,
        payloadHash: "hash_doc_003_remote",
      },
    ],
  },
  write_004: {
    rows: [
      {
        databaseId: "db_agent_001",
        table: "documents",
        primaryKey: "doc_004",
        remoteVersion: 6,
        lastUpdatedAt: "2026-07-06T08:55:00.000Z",
        schemaVersion: 5,
        payloadHash: "hash_doc_004_remote",
      },
    ],
  },
  write_005: {
    rows: [
      {
        databaseId: "db_agent_001",
        table: "projects",
        primaryKey: "project_001",
        remoteVersion: 3,
        lastUpdatedAt: "2026-07-06T08:57:00.000Z",
        schemaVersion: 5,
        payloadHash: "hash_project_001_remote",
      },
    ],
  },
  write_006: {
    rows: [
      {
        databaseId: "db_agent_001",
        table: "vector_memory",
        primaryKey: "memory_001",
        remoteVersion: 21,
        lastUpdatedAt: "2026-07-06T08:54:00.000Z",
        schemaVersion: 5,
        payloadHash: "hash_memory_001_remote",
      },
    ],
  },
  write_007: {
    rows: [
      {
        databaseId: "db_agent_001",
        table: "tasks",
        primaryKey: "task_001",
        remoteVersion: 8,
        lastUpdatedAt: "2026-07-06T08:53:00.000Z",
        schemaVersion: 5,
        payloadHash: "hash_task_001_remote",
      },
    ],
  },
  write_008: {
    rows: [
      {
        databaseId: "db_agent_001",
        table: "sessions",
        primaryKey: "session_001",
        remoteVersion: 6,
        lastUpdatedAt: "2026-07-06T08:52:00.000Z",
        schemaVersion: 5,
        payloadHash: "hash_session_001_remote",
      },
    ],
  },
  write_009: {
    rows: [
      {
        databaseId: "db_agent_001",
        table: "notes",
        primaryKey: "note_001",
        remoteVersion: 14,
        lastUpdatedAt: "2026-07-06T08:51:00.000Z",
        schemaVersion: 5,
        payloadHash: "hash_note_001_remote",
      },
    ],
  },
  write_010: {
    rows: [
      {
        databaseId: "db_agent_001",
        table: "batch_items",
        primaryKey: "batch_001",
        remoteVersion: 20,
        lastUpdatedAt: "2026-07-06T08:50:00.000Z",
        schemaVersion: 5,
        payloadHash: "hash_batch_001_remote",
      },
    ],
  },
  write_011: {
    rows: [
      {
        databaseId: "db_agent_001",
        table: "batch_items",
        primaryKey: "batch_002",
        remoteVersion: 21,
        lastUpdatedAt: "2026-07-06T08:49:00.000Z",
        schemaVersion: 5,
        payloadHash: "hash_batch_002_remote",
      },
    ],
  },
  write_012: {
    rows: [
      {
        databaseId: "db_agent_001",
        table: "cache_entries",
        primaryKey: "cache_001",
        remoteVersion: 18,
        lastUpdatedAt: "2026-07-06T08:48:00.000Z",
        schemaVersion: 5,
        payloadHash: "hash_cache_001_remote",
      },
    ],
  },
};

export const mockRemoteMetadata: Record<string, RemoteMetadata> = {
  write_001: {
    remoteAvailable: true,
    authValid: true,
    currentSchemaVersion: 5,
    lastPullVersion: 10,
    embeddingModelVersion: 4,
    remoteApplyHealthy: true,
  },
  write_002: {
    remoteAvailable: false,
    authValid: true,
    currentSchemaVersion: 5,
    lastPullVersion: 11,
    embeddingModelVersion: 4,
    remoteApplyHealthy: true,
  },
  write_003: {
    remoteAvailable: true,
    authValid: true,
    currentSchemaVersion: 5,
    lastPullVersion: 12,
    embeddingModelVersion: 4,
    remoteApplyHealthy: true,
  },
  write_004: {
    remoteAvailable: true,
    authValid: true,
    currentSchemaVersion: 5,
    lastPullVersion: 6,
    embeddingModelVersion: 4,
    remoteApplyHealthy: true,
  },
  write_005: {
    remoteAvailable: true,
    authValid: true,
    currentSchemaVersion: 5,
    lastPullVersion: 3,
    embeddingModelVersion: 4,
    remoteApplyHealthy: true,
  },
  write_006: {
    remoteAvailable: true,
    authValid: true,
    currentSchemaVersion: 5,
    lastPullVersion: 21,
    embeddingModelVersion: 4,
    remoteApplyHealthy: true,
  },
  write_007: {
    remoteAvailable: true,
    authValid: true,
    currentSchemaVersion: 5,
    lastPullVersion: 8,
    embeddingModelVersion: 4,
    remoteApplyHealthy: true,
  },
  write_008: {
    remoteAvailable: true,
    authValid: false,
    currentSchemaVersion: 5,
    lastPullVersion: 6,
    embeddingModelVersion: 4,
    remoteApplyHealthy: true,
  },
  write_009: {
    remoteAvailable: true,
    authValid: true,
    currentSchemaVersion: 5,
    lastPullVersion: 11,
    embeddingModelVersion: 4,
    remoteApplyHealthy: true,
  },
  write_010: {
    remoteAvailable: true,
    authValid: true,
    currentSchemaVersion: 5,
    lastPullVersion: 20,
    embeddingModelVersion: 4,
    remoteApplyHealthy: true,
  },
  write_011: {
    remoteAvailable: true,
    authValid: true,
    currentSchemaVersion: 5,
    lastPullVersion: 21,
    embeddingModelVersion: 4,
    remoteApplyHealthy: false,
  },
  write_012: {
    remoteAvailable: true,
    authValid: true,
    currentSchemaVersion: 5,
    lastPullVersion: 16,
    embeddingModelVersion: 4,
    remoteApplyHealthy: true,
  },
};

export const mockRemoteContextByWriteId: Record<
  string,
  {
    remoteState: RemoteState;
    remoteMetadata: RemoteMetadata;
  }
> = Object.fromEntries(
  Object.keys(mockRemoteStates).map((writeId) => [
    writeId,
    {
      remoteState: mockRemoteStates[writeId] as RemoteState,
      remoteMetadata: mockRemoteMetadata[writeId] as RemoteMetadata,
    },
  ]),
) as Record<
  string,
  {
    remoteState: RemoteState;
    remoteMetadata: RemoteMetadata;
  }
>;
